- wgpu-mc/src/camera.rs
- wgpu-mc/src/lib.rs
- wgpu-mc/src/mc/block.rs
- wgpu-mc/src/mc/chunk.rs
- wgpu-mc/src/mc/datapack/mod.rs
- wgpu-mc/src/mc/entity.rs
- wgpu-mc/src/mc/gui.rs
- wgpu-mc/src/mc/mod.rs
- wgpu-mc/src/mc/resource.rs
- wgpu-mc/src/model.rs
- wgpu-mc/src/texture.rs
I've done quite a lot here:
- Reformat code with `cargo fmt`.
- Remove unnecessary `use` statements.
- Tag dead code with `#[allow()]` tags, and marked each one with a `// TODO` comment
- Replaced some `<iterator>.for_each(<..>)` statements with `for <..> in <iterator>` expression
- Replaced some `match` expressions with `if let`
- Removed some unnecessary allocations (this one might actually make a difference to the generated code lmao)
I also applied some clippy lints.
In general, I've just made the code more readable, and maybe a little bit faster.
> Cleanup code

- wgpu-mc/src/camera.rs
- wgpu-mc/src/lib.rs
- wgpu-mc/src/mc/block.rs
- wgpu-mc/src/mc/chunk/mod.rs
- wgpu-mc/src/mc/datapack/mod.rs
- wgpu-mc/src/mc/mod.rs
- wgpu-mc/src/model.rs
- wgpu-mc/src/render/atlas.rs
- wgpu-mc/src/render/chunk/mod.rs
- wgpu-mc/src/render/pipeline/mod.rs
- wgpu-mc/src/render/shader.rs
- wgpu-mc/src/texture.rs
Just minor edits that don't alter behavior based on feedback from clippy.
> Some clippy housekeeping

- fabric/src/main/java/dev/birb/wgpu/input/WgpuKeys.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/InputUtilMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/KeyboardMixin.java
- fabric/src/main/java/dev/birb/wgpu/render/Wgpu.java
- fabric/src/main/resources/wgpu.mixins.json
- fabric/src/main/resources/wgpu_mc.accesswidener
- rust/wgpu-mc-jni/src/lib.rs
Basic keyboard is implemented, able to type simple stuff in menus like the add server menu.
> Basic keyboard input

- fabric/src/main/java/dev/birb/wgpu/mixin/core/InputUtilMixin.java
- fabric/src/main/java/dev/birb/wgpu/rust/WgpuNative.java
- fabric/src/main/java/dev_birb_wgpu_rust_Wgpu.h
- rust/wgpu-mc-jni/src/lib.rs
Fixes crashes when the game tries to set the mouse mode and position.
> Fix mouse crash

- .github/workflows/rust-check.yml
- rust/wgpu-mc-demo/src/chunk/mod.rs
- rust/wgpu-mc-demo/src/entity/mod.rs
- rust/wgpu-mc-demo/src/main.rs
- ran `cargo fmt`
- add rust ci checks from https://github.com/booyaa/gh-actions-template-rust
> add rust ci and format code with rustfmt

- fabric/src/main/java/dev/birb/wgpu/Options.java
- fabric/src/main/java/dev/birb/wgpu/Utils.java
- fabric/src/main/java/dev/birb/wgpu/gui/OptionPageScreen.java
- fabric/src/main/java/dev/birb/wgpu/gui/OptionPages.java
- fabric/src/main/java/dev/birb/wgpu/gui/TextRendererAccessor.java
- fabric/src/main/java/dev/birb/wgpu/gui/WidgetRenderer.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/BoolOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/EnumOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/IntOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/Option.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/BoolWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/CustomButtonWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/EnumWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/IOptionWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/IntWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/TabWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/TextWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/TooltipWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/Widget.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/OptionsScreenMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/TextRendererMixin.java
- fabric/src/main/resources/wgpu.mixins.json
Tooltips for options are missing but the implementation for them is there and fully working. Also currently the ELectrum specific options are just stored inside `Options` class and not saved anywhere. Apart from that everything is done.
> Added custom video options GUI

- rust/wgpu-mc/src/lib.rs
> Use RwLock instead of ArcSwap for surface_config

- rust/wgpu-mc-jni/src/renderer.rs
> Fix deadlock

- fabric/src/main/java/dev/birb/wgpu/gui/OptionPages.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/BoolOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/FloatOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/IntOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/Option.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/RustOptionInfo.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/TextEnumOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/FloatWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/TextEnumWidget.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/MainMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/MinecraftClientCoreMixin.java
- fabric/src/main/java/dev/birb/wgpu/rust/WgpuNative.java
- rust/wgpu-mc-jni/Cargo.toml
- rust/wgpu-mc-jni/src/lib.rs
- rust/wgpu-mc-jni/src/renderer.rs
- rust/wgpu-mc-jni/src/settings.rs
- rust/wgpu-mc/src/mc/chunk/mod.rs
- rust/wgpu-mc/src/render/world/chunk.rs
> :sparkles: Start work on settings system

- rust/wgpu-mc-demo/src/chunk/mod.rs
- rust/wgpu-mc-demo/src/main.rs
- rust/wgpu-mc-jni/src/gl/pipeline.rs
- rust/wgpu-mc-jni/src/lib.rs
- rust/wgpu-mc-jni/src/renderer.rs
- rust/wgpu-mc/src/lib.rs
- rust/wgpu-mc/src/mc/chunk/mod.rs
- rust/wgpu-mc/src/mc/entity.rs
- rust/wgpu-mc/src/mc/mod.rs
- rust/wgpu-mc/src/render/graph.rs
- rust/wgpu-mc/src/render/pipeline/debug_lines.rs
- rust/wgpu-mc/src/render/pipeline/mod.rs
- rust/wgpu-mc/src/render/world/chunk.rs
- rust/wgpu-mc/src/texture.rs
this pr should make CI happy again
> fix clippy issues

- rust/wgpu-mc-jni/src/lib.rs
This bothered me a bit so I just went ahead and optimized it as much as possible. It's just some trickery with shifting bits.. can't get much faster! The infamous issue is now only a 2 line fix, haha.
> Better way of handling the neighbor chunk flooring

- .github/workflows/build.yml
- .github/workflows/rust-check.yml
> [CI] Fix Double Run on PR

- fabric/src/main/java/dev/birb/wgpu/gui/OptionPageScreen.java
- fabric/src/main/java/dev/birb/wgpu/gui/OptionPages.java
- fabric/src/main/java/dev/birb/wgpu/gui/WidgetRenderer.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/EnumOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/FloatOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/IntOption.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/Option.java
- fabric/src/main/java/dev/birb/wgpu/gui/options/RustOptionInfo.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/FloatWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/IntWidget.java
- fabric/src/main/java/dev/birb/wgpu/gui/widgets/Widget.java
- fabric/src/main/java/dev/birb/wgpu/mixin/TitleScreenMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/GlStateManagerMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/OptionsScreenMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/RegistryMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/BufferRendererMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/GameRendererCameraMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/InGameHudMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/WindowFramebufferMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/WindowMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/render/WorldRendererMixin.java
- fabric/src/main/java/dev/birb/wgpu/rust/WgpuNative.java
- fabric/src/main/java/dev/birb/wgpu/rust/WgpuResourceProvider.java
- fabric/src/main/resources/fabric.mod.json
- fabric/src/main/resources/wgpu_mc.accesswidener
- gradle.properties
- rust/wgpu-mc/Cargo.toml
Updates the game to 1.20.1. That's it.
The game's code changed significantly since 1.18.1 in many ways (mostly beneficial), and I feel like it's just a good idea in general to keep the mod up to date progressively as new Minecraft versions release to avoid accumulating technical debt and not be like "hey guys we're 5 major versions behind" when this is eventually done
For now this is just a straight port that is meant to *just work*, but the config/option system by MineGame159 could use some changes to work better with 1.19's new `SimpleOption`.
> Update to Minecraft 1.20.1

- fabric/src/main/java/dev/birb/wgpu/mixin/core/MainMixin.java
- fabric/src/main/java/dev/birb/wgpu/mixin/core/MinecraftClientCoreMixin.java
- fabric/src/main/java/dev/birb/wgpu/rust/WgpuNative.java
- rust/wgpu-mc-jni/src/renderer.rs
- fix crash when trying to exit the game
- fix 'Quit Game' button hanging
> fix game exit

- fabric/src/main/java/dev/birb/wgpu/mixin/render/BufferRendererMixin.java
- rust/wgpu-mc-jni/src/lib.rs
I can't believe the most major bugs has had the most simplest of fixes thus far
> Fix title screen panorama

- rust/wgpu-mc-demo/src/main.rs
- rust/wgpu-mc-jni/src/renderer.rs
- rust/wgpu-mc/src/lib.rs
Made a quick fix for this issue, feel free to organize a tad bit more. Just swapped the surface reconfiguration from the window event to the main game loop, using the window event to update the size variable. It appeared that wgpu was trying to create a new swapchain before the windowevent could update the size when resizing the window.
> Fix resizing the window causing outdated swapchain

- fabric/src/main/java/dev/birb/wgpu/render/Wgpu.java
- rust/wgpu-mc-jni/src/lib.rs
uh mouse capture works on macos now, but I possibly broke it for all the other OSes pls test and fix :)))))
> fix macOS cursor grabbing issues

- fabric/src/main/java/dev/birb/wgpu/mixin/render/WindowMixin.java
- fabric/src/main/java/dev/birb/wgpu/render/Wgpu.java
You don't really need any values for the window to function (as we use winit anyways), so I just cleared out the defaults.
> Fix unsupported resolution popup

- fabric/src/main/java/dev/birb/wgpu/mixin/render/WindowMixin.java
bruh its hard to see without my glasses
Fixes #96
> Fix GUI scaling option

- .github/workflows/build.yml
what was supposed to be a quick "just fix the artifact uploading" PR somehow turned into a general build.yml workflow cleanup 😅
> CI: Fix artifact uploading and generally improve the `build` workflow

- rust/Cargo.lock
- rust/wgpu-mc-jni/Cargo.toml
- rust/wgpu-mc-jni/src/glfw.rs
- shell.nix
Fixes a compile error due to leaking mac dependencies and opens an X11 window on linux
> Adapt glfw code to work on linux
